[lint]
ignore = [
    "BLE001",
    "DTZ003",
    "LOG015",
    "TRY002",
    "S110",
    "SIM117",
    "ASYNC230",
    "RUF012",
    "RUF013",
    "RUF059",
    "B023",
    "TRY201",
    "F841",
    "F401"
]
